"""
Django settings for setup project.

Generated by 'django-admin startproject' using Django 6.0.5.
"""

from pathlib import Path
from datetime import timedelta
import os
import dj_database_url # <-- Permite ler a URL do PostgreSQL da nuvem
from dotenv import load_dotenv # <-- NOVO: Importa a biblioteca para ler o .env local

# <-- NOVO: Carrega as variáveis do arquivo .env para o sistema local (Windows)
load_dotenv() 

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
# Na nuvem, o ideal é puxar isso de uma variável de ambiente por segurança
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-sua-chave-generica-aqui')

# SECURITY WARNING: don't run with debug turned on in production!
# Em produção isso vira False automaticamente se a variável existir
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = ['*'] # Deixando aberto para facilitar o desenvolvimento com o frontend local e nuvem

# --- CONFIGURAÇÕES DE SEGURANÇA (CSRF) ---
# Libera o login no painel de administrador através dos links da nuvem
CSRF_TRUSTED_ORIGINS = [
    'https://arkanumtarot-production.up.railway.app',
    'https://arkanumtarot.com.br',
    'https://www.arkanumtarot.com.br',
]

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'assinaturas',
    
    # --- BIBLIOTECAS DE TERCEIROS ---
    'rest_framework',
    'corsheaders',
    'rest_framework_simplejwt',
    
    # --- APPS DO ARCANUM ---
    'api',
    'users',
    'tiragens',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # <-- WhiteNoise para servir os arquivos estáticos rápido
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # Middleware do CORS acima do CommonMiddleware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'setup.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'setup.wsgi.application'

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# Se tiver a variável DATABASE_URL (nuvem) ele usa Postgres. Se não tiver (sua máquina), usa SQLite.
DATABASES = {
    'default': dj_database_url.config(
        default='sqlite:///' + str(BASE_DIR / 'db.sqlite3'),
        conn_max_age=600,
        conn_health_checks=True,
    )
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/
LANGUAGE_CODE = 'pt-br'
TIME_ZONE = 'America/Sao_Paulo'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles' # Onde a nuvem vai empacotar os arquivos
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage' # Compacta e acelera a entrega

# --- CONFIGURAÇÕES EXTRAS DO ARCANUM ---

# 1. Modelo de Usuário Customizado para Autenticação
AUTH_USER_MODEL = 'users.CustomUser'

# 2. Diretórios de Armazenamento de Arquivos de Mídia (Uploads de Áudio e Imagem)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- 3. CONFIGURAÇÕES DO CORS (Comunicação com o Frontend) ---
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "https://arkanumtarot.com.br",        # <-- Domínio oficial liberado!
    "https://www.arkanumtarot.com.br",
]
CORS_ALLOW_CREDENTIALS = True

# --- 4. CONFIGURAÇÕES DO DJANGO REST FRAMEWORK & SIMPLE JWT ---
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),     # Tempo de expiração do token de acesso
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),    # Tempo de expiração do token de renovação
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),               # Prefixo usado no header Authorization das requisições
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}