# Generated by Django 6.0.5 on 2026-05-28 01:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tiragens', '0003_registroakashico_data_liberacao_resumo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(choices=[('carteira', 'Carteira Virtual (Saque Manual)'), ('split_mp', 'Split Automático (Mercado Pago)')], default='carteira', max_length=20)),
                ('chave_pix', models.CharField(blank=True, help_text='Chave PIX para receber os saques manuais', max_length=255, null=True)),
                ('mp_access_token', models.CharField(blank=True, max_length=255, null=True)),
                ('mp_user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financeiro', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Saque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('chave_pix_destino', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pendente', 'Aguardando Transferência'), ('pago', 'Pagamento Realizado')], default='pendente', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pago_em', models.DateTimeField(blank=True, null=True)),
                ('tarologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saques', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mp_id', models.CharField(blank=True, max_length=255, null=True)),
                ('valor_total', models.DecimalField(decimal_places=2, help_text='O que o cliente pagou', max_digits=10)),
                ('valor_plataforma', models.DecimalField(decimal_places=2, help_text='Lucro líquido do Arcanum', max_digits=10)),
                ('valor_tarologo', models.DecimalField(decimal_places=2, help_text='O que vai para o Guia', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Aguardando Pagamento'), ('approved', 'Pagamento Aprovado'), ('rejected', 'Pagamento Recusado'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
                ('metodo', models.CharField(default='pix', max_length=20)),
                ('tipo_repasse', models.CharField(choices=[('carteira', 'Carteira Virtual (Saque Manual)'), ('split_mp', 'Split Automático (Mercado Pago)')], max_length=20)),
                ('qr_code', models.TextField(blank=True, null=True)),
                ('qr_code_base64', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to=settings.AUTH_USER_MODEL)),
                ('sessao', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamento', to='tiragens.sessao')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
