# Generated by Django 6.0.5 on 2026-05-27 17:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('EXPRESSA', 'Tiragem Expressa'), ('AGENDADA', 'Sessão Agendada')], max_length=20)),
                ('status_sessao', models.CharField(choices=[('aguardando_guia', 'Na Fila de Espera'), ('agendada', 'Agendada para o Futuro'), ('ao_vivo', 'Em Andamento / Chat Aberto'), ('finalizada', 'Finalizada')], default='aguardando_guia', max_length=20)),
                ('pergunta_principal', models.CharField(max_length=255)),
                ('contexto', models.TextField()),
                ('imagem_anexa', models.ImageField(blank=True, null=True, upload_to='tiragens/anexos/')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_agendada', models.DateTimeField(blank=True, null=True)),
                ('nota', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('consulente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes_como_cliente', to=settings.AUTH_USER_MODEL)),
                ('tarologo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessoes_como_guia', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAkashico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumo_leitura', models.TextField(help_text='Resumo escrito pelo tarólogo ou gerado por IA')),
                ('cartas_tiradas', models.JSONField(help_text="Lista de strings com as cartas. Ex: ['O Louco', 'A Morte']")),
                ('data_arquivamento', models.DateTimeField(auto_now_add=True)),
                ('sessao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registro_akashico', to='tiragens.sessao')),
            ],
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('texto', 'Texto'), ('audio', 'Áudio')], default='texto', max_length=10)),
                ('texto', models.TextField(blank=True, null=True)),
                ('arquivo_audio', models.FileField(blank=True, null=True, upload_to='chat/audios/')),
                ('duracao_audio', models.CharField(blank=True, max_length=10, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='tiragens.sessao')),
            ],
            options={
                'ordering': ['criado_em'],
            },
        ),
    ]
