# Generated by Django 6.0.5 on 2026-05-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiragens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessao',
            name='ultimo_acesso_consulente',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessao',
            name='ultimo_acesso_tarologo',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
