# Generated by Django 6.0.5 on 2026-05-28 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiragens', '0002_sessao_ultimo_acesso_consulente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroakashico',
            name='data_liberacao_resumo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registroakashico',
            name='processando_ia',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registroakashico',
            name='cartas_tiradas',
            field=models.JSONField(default=list, help_text="Lista de strings com as cartas. Ex: ['O Louco', 'A Morte']"),
        ),
        migrations.AlterField(
            model_name='registroakashico',
            name='resumo_leitura',
            field=models.TextField(blank=True, help_text='Resumo escrito pelo tarólogo ou gerado por IA', null=True),
        ),
    ]
