# Generated by Django 6.0.5 on 2026-05-28 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiragens', '0003_registroakashico_data_liberacao_resumo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessao',
            name='status_sessao',
            field=models.CharField(choices=[('aguardando_pagamento', 'Aguardando Pagamento'), ('aguardando_guia', 'Na Fila de Espera'), ('agendada', 'Agendada para o Futuro'), ('ao_vivo', 'Em Andamento / Chat Aberto'), ('finalizada', 'Finalizada')], default='aguardando_pagamento', max_length=20),
        ),
    ]
