# Generated by Django 6.0.5 on 2026-05-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiragens', '0004_alter_sessao_status_sessao'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessao',
            name='valor_cobrado',
            field=models.DecimalField(decimal_places=2, default=35.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sessao',
            name='tipo',
            field=models.CharField(max_length=100),
        ),
    ]
