# Generated by Django 6.0.5 on 2026-05-28 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarologoprofile',
            name='foto_perfil',
        ),
        migrations.AddField(
            model_name='customuser',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/', verbose_name='Foto de Perfil'),
        ),
        migrations.CreateModel(
            name='AgendaTarologo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracao_sessao', models.IntegerField(default=30, help_text='Duração em minutos (ex: 15, 30, 45, 60)')),
                ('intervalo', models.IntegerField(default=10, help_text='Intervalo de respiro entre sessões em minutos')),
                ('tarologo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to='users.tarologoprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Folga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folgas', to='users.agendatarologo')),
            ],
        ),
        migrations.CreateModel(
            name='TransacaoFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada (Pagamento de Sessão)'), ('SAQUE', 'Saque para Conta Bancária')], max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.CharField(help_text='Ex: Sessão Expressa - Mariana R.', max_length=255)),
                ('status', models.CharField(choices=[('PROCESSANDO', 'Processando'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='CONCLUIDO', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('tarologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='users.tarologoprofile')),
            ],
            options={
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='TurnoTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda'), (1, 'Terça'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='users.agendatarologo')),
            ],
        ),
    ]
