# Generated by Django 6.0.5 on 2026-05-28 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_tarologoprofile_foto_perfil_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plano', models.CharField(choices=[('PREMIUM_CONSULENTE', 'Premium Consulente'), ('PRO_TAROLOGO', 'Pro Tarólogo')], max_length=30)),
                ('ativo', models.BooleanField(default=False)),
                ('data_expiracao', models.DateTimeField(blank=True, null=True)),
                ('pagamento_id', models.CharField(blank=True, help_text='ID externo da plataforma de pagamento', max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assinatura', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
