# Generated by Django 6.0.5 on 2026-05-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_assinatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assinatura',
            name='plano',
            field=models.CharField(choices=[('ESSENCIAL_CONSULENTE', 'Jornada Essencial'), ('CIRCULO_ARCANO_CONSULENTE', 'Círculo Arcano'), ('PRO_TAROLOGO', 'Guia PRO'), ('MESTRE_TAROLOGO', 'Mestre Arcano')], max_length=50),
        ),
    ]
