# Generated by Django 6.0.5 on 2026-05-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_assinatura_plano'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarologoprofile',
            name='tipos_tiragem',
            field=models.JSONField(blank=True, default=list, help_text='Lista de tiragens personalizadas do tarólogo e seus respectivos valores.'),
        ),
    ]
