# Generated by Django 6.0.5 on 2026-05-30 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_tarologoprofile_tipos_tiragem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacaofinanceira',
            name='descricao',
            field=models.CharField(help_text='Ex: Saque para Pix (email@pix.com)', max_length=255),
        ),
    ]
